language: node_js
node_js:
- '12.22.11'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=tagandpass)
  - secure: pirKwSxx9K05+Isuv4lmCRRDWW/Z0fDDGdKm4LlO2g8G2o3YuYzgAyMTVLNgo0APPfJ0UjVquZH/RdWtKGLroUJLHZbJUyByThOO5DTCmEUXIkbAC5QvgqTCjtzQrpYyEscFb3tWQoZC+276TOkn0ggTOeOm+debZTWlSVZMW1No/I+Hd3nxlGHwjvrT63H3hXbfPeuMIrYnDVziaVWjGEW1kMpp0A02VldZj1ukpOZLOHGQnbCtATXOS5LPznZgtYSKHrvcad2DEeIu0bKpotM7IOtEdxHsCvDb38AmciNgYT6Q/NNaN4F/qZ/r2HAQ0bjGSR54vGNVE24SeiObSyJRFLTpUXp/w2OYLmSJ4k9+ynI/qEhwvUhBRNU0Vl0pQsT35dathzr8yd+tULltMLJp4gk5MDhFtGZNtDOW3kJPi9ywcDfIDzkXlg/t1Z2Q5Q8HjvtbdQJmjnP5KA+uHEyU991wvrKfk0BasC8TWOXyxVKsafyuk2QmaaT+fpMfr/JYJs95YuxeFqBsHUN8kgnvBZKYKWZ0LSke2mpl8MOSv9MrxNZuGmFKvn65eY508tNbiGrwzNrvPglmjFqCeMTzNNOPvQTxsD+E9tcou6Z9gLnaxydx9Z7PRWfk5SQuVAj/o9tLErH6gQfZ3ZrlIPml5Ey32D0Ae+3vYN//iuA=
  # MATTERMOST_HOOK_URL
  - secure: uZsThhgatPTryeK0hraXRwEETwxbSKek75SwBH1yPuWfeKrQMsxTRhnghpZeqwwKSyTfLLZitYoxnUgE5sS0Gfx8xcGEjhez0lLYDohZVYNzd1bgR/xiPlC9/W8SNTOX0NjDzP/H6G06ZxDrLfzJ7oy5t1/QUm2TmXIKGh2d1zv8R3iR28u+ZJTrAerNH+pKdwscpsvQIJlCpWU0fMT9i5nbmm0Lz1cJ55xTUt1YaMzC6BjY1f8NNncf3iHxvHsRoigv16jGhIhXXYEn/ASpeuXdEnYvw5jikLJYE9t85DoR63qrhvFN8BN86/EGsHW6Ktj2WXCeFWxOXSwv5Khl8OrGiKRczzotL8+9+TWEoz+OBFRHc7W8gqtP28lJW27rScW94kt7khdWhGuVSU+RMgG+evTXXjKRWqEI3zMd93o+sR5WmOnpxjEvK6mYwBW8h+TX/nGra6xadi2M91qr+Bg4bkPeFSvSs1eNxfdZnXDG/PyevPH29AsKTCpX7Rhp+NNXh7e4d46Ae8U4WcLfJctL1rNVCaICkCoN7hYVLGNivGDjXQzLUN1G4ZcaO5m0nisjeG8k2jBTq8UeJ2tPojYPQEtcV9lZIrvVgJYCZEDSv3NxS+RlzFC0TqGbzyz5By9N6+PicZ1REdYPZXdiuHT1sHyvz2TTx2iX8wnBTXU=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_41be6ea556c7_key -iv $encrypted_41be6ea556c7_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
